In [2]:
import numpy as np
import numpy.random as rd

In [3]:
#Crea una matrice 3x3 con valori compresi tra 0 e 8

In [4]:
x = np.arange(9).reshape(3, 3) 

x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
#Crea un vettore random con 30 elementi e trova il valore medio

In [6]:
y = rd.randint(0, 100,(30))

y

array([49, 38, 65, 85, 49,  1, 63,  2, 69, 60, 35, 40, 93, 88,  0,  1, 51,
       62, 35, 78,  2, 88, 33, 47, 54, 24, 37, 31, 43, 32])

In [7]:
def media(y):
    a = 0
    b = 0
    for i in y:
        a = a + i
        b += 1        
    return a/b

In [8]:
media(y)

45.166666666666664

In [9]:
print('Media : ', (y.sum())/y.size) #metodo più generico

Media :  45.166666666666664


In [10]:
#Trova gli indici degli elementi diversi da zero del seguente array [3,5,0,4,0,8,0]

In [62]:
z = np.array([3, 5, 0, 4, 0, 8, 0])

z, type(z)


(array([3, 5, 0, 4, 0, 8, 0]), numpy.ndarray)

In [12]:
c = -1
for i in z:
    c += 1
    if i != 0:
        print("all'indice {} si trova il valore diverso da zero {}".format(c, i))

all'indice 0 si trova il valore diverso da zero 3
all'indice 1 si trova il valore diverso da zero 5
all'indice 3 si trova il valore diverso da zero 4
all'indice 5 si trova il valore diverso da zero 8


In [63]:
for i in z:                       #per array con più elementi
    if i != 0:
        b = np.where(i == z)
        print(b)

(array([0], dtype=int64),)
(array([1], dtype=int64),)
(array([3], dtype=int64),)
(array([5], dtype=int64),)


In [14]:
#Scrivi un programma per ottenere gli indici degli elementi ordinati di un dato array ,esempio :
 # -array: [1023 5202 6230 1671 1682 5241 4532]
 # -indice degli elementi ordinati dell'array :[0 3 4 6 1 5 2]

In [15]:
q = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [16]:
q

array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [30]:
np.sort(q)

array([1023, 1671, 1682, 4532, 5202, 5241, 6230])

In [19]:
np.argsort(q)

array([0, 3, 4, 6, 1, 5, 2], dtype=int64)

In [36]:
[q[0] for q in sorted(enumerate(q), key=lambda x:x[1])]   

#enumerate conta e assegna il valore della posizione/indice
#key = lamba crea una funzione anonima (che è callable)

[0, 3, 4, 6, 1, 5, 2]

In [21]:
#scrivi un programma che calcola la media attraverso la dimensione, in un array 2D

In [57]:
f = np.arange(4).reshape(2,2)

f

array([[0, 1],
       [2, 3]])

In [24]:
def medie(f):
    print('media di ogni colonna ',(f.sum(axis=0))/2)
    print('media di ogni riga', (f.sum(axis=1))/2)

#Per array con più dimensioni fare un ciclio dove il numero
#di axis aumenta fino a ranggiungere la dimenisone e dividere per quel valore

In [25]:
medie(f)

media di ogni colonna  [1. 2.]
media di ogni riga [0.5 2.5]


In [26]:
g = rd.randint(1,100,(2,2))

print(g, '\n'),
medie(g)

[[15 79]
 [78 10]] 

media di ogni colonna  [46.5 44.5]
media di ogni riga [47. 44.]
